/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiagonAlleyUI.java
 *
 * Created on Apr 11, 2009, 2:55:16 PM
 */

package client;



import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import library.EveryoneRef;
import library.MagicalItemInfo;
import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel;
import org.jvnet.substance.skin.SubstanceBusinessLookAndFeel;


/**
 *
 * @author karthik
 */
public class DiagonAlleyUINew extends javax.swing.JFrame {
    static String userName = null;
    static boolean isWizard = false;
    static EveryoneRef er= null;
    static int price, quantity, magicalItemNumber = 0;
    static long msec;
    static boolean isBid = false;
    static SwingWorker scoreWorker = null;
    static SwingWorker cilTableWorker = null;
    static SwingWorker dailyProphetWorker = null;
    /** Creates new form DiagonAlleyUI */
    public DiagonAlleyUINew() {
        initComponents();
    }

    /* Creates new Instance of DiagonAlleyUI JFrame */
    public static DiagonAlleyUINew newInstance() {
        DiagonAlleyUINew diagonAlleyUI = new DiagonAlleyUINew();
        return diagonAlleyUI;
    }

    /* Returns the assignedAs label */
    public javax.swing.JLabel getAssignedAsLabel() {
        return this.assignedAs;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        assignedAs = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mytask = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        score = new javax.swing.JLabel();
        bidTradeDetails = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        priceField = new javax.swing.JFormattedTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        quantityField = new javax.swing.JFormattedTextField();
        submitButton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        timeField = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dailyProphet = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioBid = new javax.swing.JRadioButton();
        jRadioTrade = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        statusMessageLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        mButton1 = new javax.swing.JRadioButton();
        mButton11 = new javax.swing.JRadioButton();
        mButton2 = new javax.swing.JRadioButton();
        mButton12 = new javax.swing.JRadioButton();
        mButton3 = new javax.swing.JRadioButton();
        mButton13 = new javax.swing.JRadioButton();
        mButton4 = new javax.swing.JRadioButton();
        mButton14 = new javax.swing.JRadioButton();
        mButton5 = new javax.swing.JRadioButton();
        mButton15 = new javax.swing.JRadioButton();
        mButton6 = new javax.swing.JRadioButton();
        mButton16 = new javax.swing.JRadioButton();
        mButton7 = new javax.swing.JRadioButton();
        mButton17 = new javax.swing.JRadioButton();
        mButton8 = new javax.swing.JRadioButton();
        mButton18 = new javax.swing.JRadioButton();
        mButton9 = new javax.swing.JRadioButton();
        mButton19 = new javax.swing.JRadioButton();
        mButton10 = new javax.swing.JRadioButton();
        mButton20 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cilTable = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel11.setText("jLabel11");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel21.setText("jLabel21");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Magical Items List"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiagonAlley Market Place");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20));
        jLabel1.setText("Welcome to DiagonAlley - Open out-cry auction");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assignment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15));
        jLabel6.setText("Assigned as: ");

        assignedAs.setFont(new java.awt.Font("Tahoma", 0, 13));
        assignedAs.setText("[WIZARD-SELLER]");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15));
        jLabel8.setText("Your Goal: ");

        mytask.setFont(new java.awt.Font("Tahoma", 0, 13));
        mytask.setText("Sell all the comodities at best price.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assignedAs)
                    .addComponent(mytask, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(assignedAs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mytask))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        nameLabel.setText("[NAME]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nameLabel)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jLabel14)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(29, 29, 29)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        score.setFont(new java.awt.Font("Tahoma", 1, 28));
        score.setForeground(java.awt.Color.red);
        score.setText("[100]");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(score)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(score)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        bidTradeDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15));
        jLabel18.setText("Place a Bid:");

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel23.setText("Price");

        priceField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                priceFieldPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel24.setText("Quantity");

        quantityField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                quantityFieldPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(quantityField, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 15));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel25.setText("Time (mins)");

        timeField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                timeFieldPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(timeField, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bidTradeDetailsLayout = new javax.swing.GroupLayout(bidTradeDetails);
        bidTradeDetails.setLayout(bidTradeDetailsLayout);
        bidTradeDetailsLayout.setHorizontalGroup(
            bidTradeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bidTradeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bidTradeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(bidTradeDetailsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bidTradeDetailsLayout.setVerticalGroup(
            bidTradeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bidTradeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bidTradeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Updates (Daly Prophet)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        dailyProphet.setColumns(20);
        dailyProphet.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        dailyProphet.setRows(10);
        dailyProphet.setWrapStyleWord(true);
        dailyProphet.setAutoscrolls(false);
        dailyProphet.setDoubleBuffered(true);
        jScrollPane3.setViewportView(dailyProphet);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        jLabel9.setText("1. Follow the steps below to participate in the auction. ");

        jLabel12.setText("3. You cannot sell an item that you dont own.");

        jLabel4.setText("2. To maximize your score try to achieve your target.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15));
        jLabel2.setText("Do you wish to buy or sell:");

        buttonGroup2.add(jRadioBid);
        jRadioBid.setText("Buy item");

        buttonGroup2.add(jRadioTrade);
        jRadioTrade.setText("Sell item");
        jRadioTrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioTrade)
                    .addComponent(jRadioBid)
                    .addComponent(jLabel2))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioBid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioTrade)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status Bar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        statusMessageLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        statusMessageLabel.setForeground(new java.awt.Color(204, 0, 0));
        statusMessageLabel.setText("Status messages ..");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Tahoma", 0, 15));

        buttonGroup.add(mButton1);
        mButton1.setText("jRadioButton1");

        buttonGroup.add(mButton11);
        mButton11.setText("jRadioButton1");

        buttonGroup.add(mButton2);
        mButton2.setText("jRadioButton2");

        buttonGroup.add(mButton12);
        mButton12.setText("jRadioButton1");

        buttonGroup.add(mButton3);
        mButton3.setText("jRadioButton1");

        buttonGroup.add(mButton13);
        mButton13.setText("jRadioButton1");

        buttonGroup.add(mButton4);
        mButton4.setText("jRadioButton1");

        buttonGroup.add(mButton14);
        mButton14.setText("jRadioButton1");

        buttonGroup.add(mButton5);
        mButton5.setText("jRadioButton1");

        buttonGroup.add(mButton15);
        mButton15.setText("jRadioButton1");

        buttonGroup.add(mButton6);
        mButton6.setText("jRadioButton1");

        buttonGroup.add(mButton16);
        mButton16.setText("jRadioButton1");

        buttonGroup.add(mButton7);
        mButton7.setText("jRadioButton1");

        buttonGroup.add(mButton17);
        mButton17.setText("jRadioButton1");

        buttonGroup.add(mButton8);
        mButton8.setText("jRadioButton1");

        buttonGroup.add(mButton18);
        mButton18.setText("jRadioButton1");

        buttonGroup.add(mButton9);
        mButton9.setText("jRadioButton1");

        buttonGroup.add(mButton19);
        mButton19.setText("jRadioButton1");

        buttonGroup.add(mButton10);
        mButton10.setText("jRadioButton1");

        buttonGroup.add(mButton20);
        mButton20.setText("jRadioButton1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15));
        jLabel10.setText("Select a magical Item:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mButton1)
                            .addComponent(mButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mButton11)
                            .addComponent(mButton12)
                            .addComponent(mButton13)
                            .addComponent(mButton14)
                            .addComponent(mButton15)
                            .addComponent(mButton16)
                            .addComponent(mButton17)
                            .addComponent(mButton18)
                            .addComponent(mButton19)
                            .addComponent(mButton20)))
                    .addComponent(jLabel10)
                    .addComponent(mButton10)
                    .addComponent(mButton9)
                    .addComponent(mButton8)
                    .addComponent(mButton7)
                    .addComponent(mButton6)
                    .addComponent(mButton5)
                    .addComponent(mButton4)
                    .addComponent(mButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton11)
                    .addComponent(mButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton2)
                    .addComponent(mButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton3)
                    .addComponent(mButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton4)
                    .addComponent(mButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton5)
                    .addComponent(mButton15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton6)
                    .addComponent(mButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton7)
                    .addComponent(mButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton8)
                    .addComponent(mButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton9)
                    .addComponent(mButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mButton10)
                    .addComponent(mButton20))
                .addGap(24, 24, 24))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items that you own", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        cilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item Name", "Quantity"
            }
        ));
        cilTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(cilTable);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modify Bid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15));
        jLabel7.setText("Enter the details below:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bidTradeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(288, 288, 288))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bidTradeDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        // Select Magical Item from Button group
        if(mButton1.isSelected())
            magicalItemNumber = 0;
        else if(mButton2.isSelected())
            magicalItemNumber = 1;
        else if(mButton3.isSelected())
            magicalItemNumber = 2;
        else if(mButton4.isSelected())
            magicalItemNumber = 3;
        else if(mButton5.isSelected())
            magicalItemNumber = 4;
        else if(mButton6.isSelected())
            magicalItemNumber = 5;
        else if(mButton7.isSelected())
            magicalItemNumber = 6;
        else if(mButton8.isSelected())
            magicalItemNumber = 7;
        else if(mButton9.isSelected())
            magicalItemNumber = 8;
        else if(mButton10.isSelected())
            magicalItemNumber = 9;
        else if(mButton11.isSelected())
            magicalItemNumber = 10;
        else if(mButton12.isSelected())
            magicalItemNumber = 11;
        else if(mButton13.isSelected())
            magicalItemNumber = 12;
        else if(mButton14.isSelected())
            magicalItemNumber = 13;
        else if(mButton15.isSelected())
            magicalItemNumber = 14;
        else if(mButton16.isSelected())
            magicalItemNumber = 15;
        else if(mButton17.isSelected())
            magicalItemNumber = 16;
        else if(mButton18.isSelected())
            magicalItemNumber = 17;
        else if(mButton19.isSelected())
            magicalItemNumber = 18;
        else if(mButton20.isSelected())
            magicalItemNumber = 19;
        else {
            this.statusMessageLabel.setText("Please complete Step 1. Select a Magical Item from the list. ");
            System.out.println("Please complete Step 1. Select a Magical Item from the list.");
        }

        // Determine if this is Bid or a trade
        if(jRadioBid.isSelected())
            isBid = true;
        else if(jRadioTrade.isSelected())
            isBid = false;
        else {
            System.out.println("Please complete Step 2. Choose if you want to buy or sell an item.");
            this.statusMessageLabel.setText("Please complete Step 2. Do you wish to buy or sell an item?");
        }
        
        // Place the bid
        if(isBid)
        {
            if(Main.placeBid(er.getID(), magicalItemNumber, price, quantity, msec)) {
                System.out.println("Bid placed successfully");
                this.statusMessageLabel.setText("Your bid has been submitted.");
                //if(scoreWorker != null) scoreWorker.execute();
            } else {
                System.out.println("Bid could not be placed");
                this.statusMessageLabel.setText(this.statusMessageLabel.getText() + "Bid couldn't be placed. Retry with valid inputs.");
            }
        }
        // Place Trade
        else if(!isBid) {
            if(Main.placeTrade(er.getID(), magicalItemNumber, price, quantity, msec)) {
                System.out.println("Transaction successful !");
                this.statusMessageLabel.setText("Your bid has been submitted.");
                //if(scoreWorker != null) scoreWorker.execute();
            } else {
                System.out.println("Transaction unsuccessful. Retry with valid inputs.");
                this.statusMessageLabel.setText(this.statusMessageLabel.getText() + "Bid couldn't be placed. Retry with valid inputs.");
            }
        }

        // Set all textboxes to NULL
        this.priceField.setText(null);
        this.quantityField.setText(null);
        this.timeField.setText(null);

}//GEN-LAST:event_submitButtonActionPerformed

    private void priceFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_priceFieldPropertyChange
        if ("value".equals(evt.getPropertyName())) {
            if(priceField != null) {
                String text = priceField.getText();
                if(!text.equals("")) {
                    try {
                        price = Integer.parseInt(text);
                        this.statusMessageLabel.setText("Status message ..");
                    } catch (Exception e) {this.statusMessageLabel.setText("Invaild input. Enter numbers only !");}
                }
            }
        }
}//GEN-LAST:event_priceFieldPropertyChange

    private void quantityFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_quantityFieldPropertyChange
        if ("value".equals(evt.getPropertyName())) {
            if(quantityField != null) {
                String text = quantityField.getText();
                if(!text.equals("")){
                    try {
                        quantity = Integer.parseInt(text);
                        this.statusMessageLabel.setText("Status message ..");
                    } catch (Exception e) {this.statusMessageLabel.setText("Invalid input. Enter numbers only !");}
                }
            }
        }
    }//GEN-LAST:event_quantityFieldPropertyChange

    private void timeFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_timeFieldPropertyChange
        if ("value".equals(evt.getPropertyName())) {
            if(timeField != null) {
                String text=timeField.getText();
                if(!text.equals("")) {
                    try {
                        msec = Integer.parseInt(text)*60*1000;
                        this.statusMessageLabel.setText("Status message ..");
                    } catch (Exception e) {this.statusMessageLabel.setText("Invalid input. Enter numbers only !");}
                }
            }
        }
    }//GEN-LAST:event_timeFieldPropertyChange

    private void jRadioTradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTradeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioTradeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
        
        //SUBSTANCE SKIN ENABLE
        javax.swing.JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            javax.swing.UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());
        } catch (Exception e) {
            System.out.println("Substance Raven Graphite failed to initialize");
        }
        //userName = args[0];
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final DiagonAlleyUINew frame = newInstance();
                MagicalItemInfo[] magicalItemInfo = null;
                
                Main.hostName = "sand.cise.ufl.edu"; // WARNING: HARDCODED !!!!
                Main.port = 3600; // WARNING: HARDCODED !!!!
                frame.setVisible(true);

                // Register User
                try {
                    frame.er = Main.registerUser(Main.hostName,Main.port, userName);
                    frame.isWizard = er.isWizard();

                } catch (Exception e) {
                    System.err.println("Client exception: " + e.toString());
                    e.printStackTrace();
                }

                // Set AssignedAs Label to WIZARD-SELLER or APPRENTICE-BUYER
                if(frame.isWizard) {
                    frame.assignedAs.setText("WIZARD-SELLER");
                    frame.mytask.setText("Sell all comodities at best price");
                }
                else {
                    frame.assignedAs.setText("APPRENTICE-BUYER");
                    frame.mytask.setText("Buy the comodity at lowest price");
                }

                // Assign goal to the Wizard-seller or Apprentice-buyer
                MagicalItemInfo miir = Main.currentCommodity(er);
                int tcost = Main.targetCost(er), tquantity = Main.targetQuantity(er);
                if(er.isWizard()) {
                    frame.mytask.setText("Selling "+tquantity+" "+miir.getName()+" and your target selling price is "+tcost);
                } else {
                    frame.mytask.setText("Buying "+tquantity+" "+miir.getName()+" and your buying price target is "+tcost);
                }


                // Populate magical Item buttons
                try {
                    magicalItemInfo = Main.mr.getAllMagicalItems();
                    frame.mButton1.setText(magicalItemInfo[0].getName());
                    frame.mButton2.setText(magicalItemInfo[1].getName());
                    frame.mButton3.setText(magicalItemInfo[2].getName());
                    frame.mButton4.setText(magicalItemInfo[3].getName());
                    frame.mButton5.setText(magicalItemInfo[4].getName());
                    frame.mButton6.setText(magicalItemInfo[5].getName());
                    frame.mButton7.setText(magicalItemInfo[6].getName());
                    frame.mButton8.setText(magicalItemInfo[7].getName());
                    frame.mButton9.setText(magicalItemInfo[8].getName());
                    frame.mButton10.setText(magicalItemInfo[9].getName());
                    frame.mButton11.setText(magicalItemInfo[10].getName());
                    frame.mButton12.setText(magicalItemInfo[11].getName());
                    frame.mButton13.setText(magicalItemInfo[12].getName());
                    frame.mButton14.setText(magicalItemInfo[13].getName());
                    frame.mButton15.setText(magicalItemInfo[14].getName());
                    frame.mButton16.setText(magicalItemInfo[15].getName());
                    frame.mButton17.setText(magicalItemInfo[16].getName());
                    frame.mButton18.setText(magicalItemInfo[17].getName());
                    frame.mButton19.setText(magicalItemInfo[18].getName());
                    frame.mButton20.setText(magicalItemInfo[19].getName());
                } catch (Exception e) {
                    System.out.println("Exception in populating magical Item");
                    e.printStackTrace();
                }


                // Set the Score Label
                frame.score.setText("100");
                // Background worker thread for score label
                scoreWorker = new SwingWorker<Void, Void>() {
                    @Override
                    public Void doInBackground() {
                        int currentScore;
                        while(frame.isVisible()) {
                              currentScore = Main.currentScore(er);
                              frame.score.setText(String.valueOf(currentScore));
                              try{
                                  Thread.sleep(1000);
                              }catch(InterruptedException ie)
                              {
                              }
                        }
                        return null;
                    }
                };
                scoreWorker.execute();

                // Populating the Current Inventory List
                final MagicalItemInfo[] magicalItemInfoName = magicalItemInfo;
                ((DefaultTableModel)frame.cilTable.getModel()).setRowCount(0);
                cilTableWorker = new SwingWorker<Void, Void>() {
              @Override
              public Void doInBackground() {
                  ArrayList<String> magicalItemName = new ArrayList();
                  ArrayList<Integer> quantity = new ArrayList();
                  int qty = 0;
                  while(frame.isVisible()) {
                      try{
                          Thread.sleep(1000);
                      for(int i=0;i<20;i++) {
                          qty = Main.getQuantity(er,i);
                          if(qty != 0) {
                              magicalItemName.add(magicalItemInfoName[i].getName());
                              quantity.add(qty);
                          }
                      }
                      ((DefaultTableModel)frame.cilTable.getModel()).setRowCount(magicalItemName.size());
                      if(magicalItemName.size() != 0) {
                          for(int i=0;i<magicalItemName.size();i++) {
                              frame.cilTable.setValueAt(magicalItemName.get(i), i, 0);
                              frame.cilTable.setValueAt(quantity.get(i), i, 1);
                          }
                      }
                      magicalItemName.clear();
                      quantity.clear();
                      Thread.sleep(1000);
                      }catch(Exception ie)
                      {
                          ie.printStackTrace();
                      }
                  }
                  return null;
                  }
              };
              cilTableWorker.execute();

              dailyProphetWorker = new SwingWorker<Void,Void>() {

                @Override
                protected Void doInBackground() throws Exception {
                    while(frame.isVisible()) {
                        try {
                            //String address = "http://www.cise.ufl.edu/~agv/log_" + String.valueOf(Main.port);
                            URL logFile = new URL("http://www.cise.ufl.edu/~agv/log_" + String.valueOf(Main.port)+ ".txt");
                            URLConnection yc = logFile.openConnection();
                            BufferedReader in = new BufferedReader(
                                                    new InputStreamReader(
                                                    yc.getInputStream()));
                            String inputLine;

                            while ((inputLine = in.readLine()) != null) {
                                System.out.println(inputLine);
                                frame.dailyProphet.setText(frame.dailyProphet.getText() + "\n" +inputLine);
                            }

                            in.close();
                            Thread.sleep(1000);
                        }catch(Exception e) {e.printStackTrace();}
                        frame.dailyProphet.setText("");
                    }
                    return null;
                }

              };
              dailyProphetWorker.execute();
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignedAs;
    private javax.swing.JPanel bidTradeDetails;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTable cilTable;
    private javax.swing.JTextArea dailyProphet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioBid;
    private javax.swing.JRadioButton jRadioTrade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton mButton1;
    private javax.swing.JRadioButton mButton10;
    private javax.swing.JRadioButton mButton11;
    private javax.swing.JRadioButton mButton12;
    private javax.swing.JRadioButton mButton13;
    private javax.swing.JRadioButton mButton14;
    private javax.swing.JRadioButton mButton15;
    private javax.swing.JRadioButton mButton16;
    private javax.swing.JRadioButton mButton17;
    private javax.swing.JRadioButton mButton18;
    private javax.swing.JRadioButton mButton19;
    private javax.swing.JRadioButton mButton2;
    private javax.swing.JRadioButton mButton20;
    private javax.swing.JRadioButton mButton3;
    private javax.swing.JRadioButton mButton4;
    private javax.swing.JRadioButton mButton5;
    private javax.swing.JRadioButton mButton6;
    private javax.swing.JRadioButton mButton7;
    private javax.swing.JRadioButton mButton8;
    private javax.swing.JRadioButton mButton9;
    private javax.swing.JLabel mytask;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JFormattedTextField quantityField;
    private javax.swing.JLabel score;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JFormattedTextField timeField;
    // End of variables declaration//GEN-END:variables

    public class URLConnectionReader {
        public URLConnectionReader newInstance() {
            return this;
        }
        public void printData() {
            try {
                //String address = "http://www.cise.ufl.edu/~agv/log_" + String.valueOf(Main.port);
                URL logFile = new URL("http://www.cise.ufl.edu/~agv/log_" + String.valueOf(Main.port));
                URLConnection yc = logFile.openConnection();
                BufferedReader in = new BufferedReader(
                                        new InputStreamReader(
                                        yc.getInputStream()));
                String inputLine;

                while ((inputLine = in.readLine()) != null) {
                    System.out.println(inputLine);
                    dailyProphet.setText(dailyProphet.getText() + "\n" +inputLine);
                }
                    
                in.close();
            }catch(Exception e) {e.printStackTrace();}
        }
    }

}
